version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/python:3.9.0
      auth:
          username: ketan3108
          password: Ketan31)*
    steps:
      - checkout
      - run: echo "this is the build job"
