version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9.0
        auth:
          username: ketan3108
          password: Ketan31)*  # context / project UI env-var reference
    steps:
      - run: pip install docker-compose
  test:
    docker:
      - image: cimg/python:3.9.0
        auth:
          username: ketan3108
          password: Ketan31)*  # context / project UI env-var reference
    steps:
      - run: docker-compose run app sh -c "python manage test"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
